"""Apply the whole race.bin patch set in one reproducible step.

WHY THIS EXISTS. The individual patches each work, but applying them by hand
leaves a binary nobody can rebuild: the order matters, two of them interact, and
every module drops its own `.backup` so an install accumulates a dozen files that
say nothing about what state it is actually in. This module fixes the order once
and rebuilds from a single pristine snapshot every time, so the same inputs always
produce the same bytes.

THE ORDER, AND WHY IT IS THIS ORDER:

    1. vram       Startup fix. Independent of everything else.
    2. tables     Doubles the rasteriser's stack frame to 2048 scanlines. Must come
                  BEFORE needle, because needle's bound has to match the tables that
                  actually exist -- and it relocates 21 displacements, so it wants a
                  function nothing else has touched yet.
    3. needle     Two rasteriser bounds, set to whatever step 2 left. Bigger tables
                  with the old bound gains nothing; a bigger bound with the old
                  tables reinstates the stack smash. They move together or not at all.
    4. aspect     Rewrites the viewport builder; may write a float into .rdata slack.
    5. resolution Immediate operands at four sites plus the menu label.
    6. mapfile    LAST, always. It is generated by scanning .text for call targets,
                  so it has to run after every byte of code has settled, and it
                  appends to the file rather than editing it.

Steps 1-5 never change the file's length; step 6 only appends past the last
section, so the image the loader sees is identical either way.

REBUILD, DON'T LAYER. `apply()` always restores the pristine snapshot first and
replays the whole set. That makes it idempotent for free, makes the result depend
only on the arguments rather than on what happened to be applied before, and
means a bad run is undone by the next good one. The alternative -- patching
whatever is currently on disk -- is how the working binary in this project ended
up unreproducible across fifteen backups.

THE SNAPSHOT. The first run copies race.bin to `race.bin.vrmod-original` and
that file is never written again. It is only taken if the binary looks untouched,
so a half-patched file cannot be captured as the baseline; `baseline()` reports
what it found. `revert()` restores it and removes the appended map.

NOT INCLUDED BY DEFAULT: the DPI-awareness flag. On a high-DPI display the game
is handed a virtualised surface smaller than the mode it asked for and draws
outside it -- see the reference, display-scaling section. That fix is a Windows
per-application setting rather than a change to any game file, so `apply()` only
reports whether it is needed; `set_dpi_aware()` writes it, and the CLI requires
an explicit flag before calling it.
"""
from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from pathlib import Path

from . import aspectfix, mapfile, needlefix, resolution, tablefix, vertexbuffer, vrampatch

RACE_BIN = "race.bin"
SNAPSHOT = "race.bin.vrmod-original"

DEFAULT_MODE = (1920, 1080)
DEFAULT_INDEX = 4               # menu index; 2 is the boot gate and must not be used


class PatchSetError(RuntimeError):
    """The install is not in a state this can safely work from."""


@dataclass
class Report:
    baseline: str = ""
    steps: list[tuple[str, str]] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def add(self, name: str, detail: str) -> None:
        self.steps.append((name, detail))


def _race_bin(data_dir: str | Path) -> Path:
    f = Path(data_dir) / RACE_BIN
    if not f.is_file():
        raise PatchSetError(f"no {RACE_BIN} in {data_dir}")
    return f


def looks_pristine(data_dir: str | Path) -> tuple[bool, str]:
    """Is this race.bin untouched by us? Returns (verdict, reason).

    The VRAM fix is deliberately not part of the test: the community v1.2.5 build
    ships with it already applied, and that build is a perfectly good baseline.
    """
    d = Path(data_dir)
    if needlefix.status(d) != needlefix.UNPATCHED:
        return False, f"needle fix is {needlefix.status(d)}"
    if aspectfix.status(d) != aspectfix.UNPATCHED:
        return False, f"aspect fix is {aspectfix.status(d)}"
    _, _, trailing = mapfile.status(d)
    if trailing:
        return False, f"{trailing:,} bytes appended after the last section (a symbol map?)"
    return True, "no vrmod patches detected"


def baseline(data_dir: str | Path) -> str:
    """Describe the snapshot this install would rebuild from."""
    d = Path(data_dir)
    snap = d / SNAPSHOT
    if snap.exists():
        return f"{SNAPSHOT} ({snap.stat().st_size:,} bytes)"
    ok, why = looks_pristine(d)
    return (f"none yet; the current race.bin would be captured ({why})" if ok
            else f"none yet, and the current race.bin is NOT clean: {why}")


def _snapshot(data_dir: Path, force: bool) -> Path:
    snap = data_dir / SNAPSHOT
    if snap.exists():
        return snap
    ok, why = looks_pristine(data_dir)
    if not ok and not force:
        raise PatchSetError(
            f"refusing to snapshot a patched race.bin as the baseline: {why}.\n"
            f"Restore an original race.bin first, or pass force=True if you are "
            f"certain this file is the one you want to rebuild from every time.")
    shutil.copy2(_race_bin(data_dir), snap)
    return snap


def status(data_dir: str | Path) -> dict[str, str]:
    """Current state of every component."""
    d = Path(data_dir)
    size, image_end, trailing = mapfile.status(d)
    try:
        modes = ", ".join(f"{m.index}:{m.width}x{m.height}" for m in resolution.modes(d))
    except Exception as exc:                       # a mode table we don't recognise
        modes = f"<{type(exc).__name__}>"
    return {
        "baseline": baseline(d),
        "vram": vrampatch.status(d),
        "tables": f"{tablefix.status(d)} ({tablefix.entries(d)} entries per table)",
        "needle": needlefix.status(d),
        "aspect": aspectfix.status(d),
        "vertices": vertexbuffer.status(d),
        "resolution": modes,
        "mapfile": f"{trailing:,} bytes appended" if trailing else "not installed",
        "size": f"{size:,} bytes",
    }


def apply(data_dir: str | Path,
          *,
          mode: tuple[int, int] = DEFAULT_MODE,
          index: int = DEFAULT_INDEX,
          with_map: bool = True,
          big_tables: bool = True,
          ratio: float = aspectfix.RATIO_ORIGINAL,
          max_verts: int | None = None,
          force_baseline: bool = False) -> Report:
    """Rebuild race.bin from the pristine snapshot with the full patch set."""
    d = Path(data_dir)
    f = _race_bin(d)
    rep = Report()

    snap = _snapshot(d, force_baseline)
    rep.baseline = f"{snap.name} ({snap.stat().st_size:,} bytes)"
    shutil.copy2(snap, f)                          # start clean, every time

    # 1 -- startup
    if vrampatch.status(d) == vrampatch.PATCHED:
        rep.add("vram", "already correct in this build (v1.2.5 ships it)")
    else:
        rep.add("vram", f"patched at {hex(vrampatch.apply(d))}")

    # 2 -- rasteriser: grow the tables first, then bound to whatever they now hold.
    #      These two MUST agree. Bigger tables with the old bound gains nothing;
    #      a bigger bound with the old tables reinstates the stack smash.
    if big_tables:
        info = tablefix.apply(d)
        if info["result"] == "patched":
            rep.add("tables", f"frame 0x2000 -> 0x4000 at {info['at']:#x}: "
                              f"{info['table_b_refs']} table-B and {info['arg_refs']} "
                              f"argument references relocated, 2048 entries each")
        else:
            rep.add("tables", str(info["result"]))
    else:
        rep.add("tables", "left at 1024 entries (--small-tables)")

    bound = tablefix.entries(d)
    for site, detail in needlefix.apply(d, entries=bound).items():
        rep.add(f"needle/{site}", detail)

    # 3 -- viewport / field of view
    at, r0, half = aspectfix.apply(d, ratio)
    rep.add("aspect", f"Hor+ at R0={ratio:.4f}, patched at {hex(at)} "
                      f"(constants {hex(r0)}, {hex(half)})")

    # 4 -- resolution
    w, h = mode
    was = resolution.set_mode(d, index, w, h)
    rep.add("resolution", f"menu index {index}: {was[0]}x{was[1]} -> {w}x{h}")
    rows = tablefix.entries(d)
    if h - 0x50 >= rows:
        rep.notes.append(
            f"{w}x{h} pivots the tachometer needle at row {h - 0x50}, past the "
            f"{rows}-scanline edge tables, so the NEEDLE will not be drawn. The dial "
            f"itself is unaffected." + ("" if big_tables else
            " Dropping --small-tables would raise the tables to 2048 and fix it."))
    if w > 2048:
        rep.notes.append(
            f"{w} is wider than 2048, which legacy Direct3D surfaces cap at. Expect "
            f"'create device' / DDERR_INVALIDOBJECT and a misleading "
            f"'requires DirectX 5 or 6' dialog from the launcher.")

    # 5b -- per-object vertex buffer (OPT-IN). Off unless a size is asked for,
    #       because the stock cap suits every stock car and raising it only helps
    #       high-poly mods (and, at worst, trades frames for detail with many such
    #       cars -- it cannot crash, rendering being per-object; see vertexbuffer).
    if max_verts is None:
        rep.add("vertices", f"left at stock ({vertexbuffer.status(d)}); "
                            f"raise with --max-verts")
    else:
        info = vertexbuffer.apply(d, max_verts)
        rep.add("vertices", f"buffer {info['old_verts']:,} -> {info['new_verts']:,} "
                            f"verts/object at {info['at']:#x}")

    # 6 -- symbols, last
    if with_map:
        syms, added = mapfile.install(d)
        rep.add("mapfile", f"{syms:,} symbols, {added:,} bytes appended")
    else:
        rep.add("mapfile", "skipped")

    if not dpi_aware(d):
        rep.notes.append(
            "This machine scales the desktop, so the game will be handed a surface "
            "smaller than the mode it asks for and will draw outside it. Set the "
            "launcher to be DPI-aware (see set_dpi_aware) before judging any "
            "high-resolution rendering.")
    return rep


def revert(data_dir: str | Path) -> str:
    """Put the pristine snapshot back."""
    d = Path(data_dir)
    snap = d / SNAPSHOT
    if not snap.exists():
        raise PatchSetError(f"no {SNAPSHOT} to restore from")
    shutil.copy2(snap, _race_bin(d))
    return f"restored {RACE_BIN} from {SNAPSHOT} ({snap.stat().st_size:,} bytes)"


# --------------------------------------------------------------------------
# the Windows side
# --------------------------------------------------------------------------

LAYERS_KEY = r"Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"
LAUNCHER = "Viper Racing.exe"


def _dpi_targets(data_dir: str | Path) -> list[Path]:
    """The executables a DPI compatibility layer may need to sit on.

    Two candidates, because which one Windows honours is genuinely ambiguous:

      * `race.bin` -- the REAL game process. `Viper Racing.exe` only
        `CreateProcess`-es it and imports no graphics DLLs, so race.bin is what
        owns the window and renders (it imports DDRAW/DSOUND). Windows tracks it
        as a program in its own right -- the Program Compatibility Assistant
        auto-adds a `DWM8And16BitMitigation` layer to the race.bin path -- so a
        layer keyed to race.bin is honoured despite the `.bin` extension.
      * `Viper Racing.exe` -- the launcher. Empirically, setting HIGHDPIAWARE
        here ALSO fixes rendering, most likely because a compatibility shim set
        on a parent propagates to the child it spawns.

    So the flag is set on both, and considered present if either has it. An
    earlier version targeted only the launcher, and named it "the process that
    owns the window", which is wrong -- race.bin is.
    """
    d = Path(data_dir)
    return [d / RACE_BIN, d.parent / LAUNCHER]


def scaling_active() -> bool | None:
    """Is the desktop being scaled for DPI-unaware processes? None if unknowable."""
    try:
        import ctypes
        user32 = ctypes.windll.user32
        virt_w = user32.GetSystemMetrics(0)                 # what an unaware app sees
        real_w = ctypes.windll.gdi32.GetDeviceCaps(
            user32.GetDC(0), 118)                           # DESKTOPHORZRES: physical
        return bool(real_w and virt_w and real_w != virt_w)
    except Exception:
        return None


def dpi_aware(data_dir: str | Path) -> bool:
    """Does race.bin OR the launcher already carry the HIGHDPIAWARE layer?

    Either is enough: race.bin is the process that renders, but a shim on the
    launcher propagates to it, and empirically that fixes rendering too.
    """
    try:
        import winreg
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, LAYERS_KEY) as k:
            for exe in _dpi_targets(data_dir):
                try:
                    if "HIGHDPIAWARE" in winreg.QueryValueEx(k, str(exe))[0]:
                        return True
                except FileNotFoundError:
                    continue
    except Exception:
        pass
    return False


def set_dpi_aware(data_dir: str | Path, enable: bool = True) -> str:
    """Add or remove the launcher's HIGHDPIAWARE layer for the current user.

    This writes to HKEY_CURRENT_USER only, affects one executable, and is exactly
    what the Compatibility tab writes when you tick "Override high DPI scaling
    behavior -- Scaling performed by: Application". Callers should make this an
    explicit choice rather than part of a default install.
    """
    import winreg
    targets = [e for e in _dpi_targets(data_dir) if e.is_file()]
    if not targets:
        raise PatchSetError(f"no {RACE_BIN} or {LAUNCHER} to flag in {data_dir}")
    key = winreg.CreateKey(winreg.HKEY_CURRENT_USER, LAYERS_KEY)
    results = []
    try:
        for exe in targets:
            try:
                current = winreg.QueryValueEx(key, str(exe))[0]
            except FileNotFoundError:
                current = ""
            # keep any existing layers (e.g. the PCA's DWM8And16BitMitigation);
            # only add or remove HIGHDPIAWARE.
            layers = [t for t in current.split() if t not in ("HIGHDPIAWARE", "~")]
            if enable:
                layers.insert(0, "HIGHDPIAWARE")
            if layers:
                winreg.SetValueEx(key, str(exe), 0, winreg.REG_SZ, " ".join(["~"] + layers))
                results.append(f"{exe.name}: {' '.join(['~'] + layers)}")
            else:
                try:
                    winreg.DeleteValue(key, str(exe))
                    results.append(f"{exe.name}: compatibility layers cleared")
                except FileNotFoundError:
                    results.append(f"{exe.name}: nothing to clear")
    finally:
        winreg.CloseKey(key)
    return "; ".join(results)
