"""Apply the whole race.bin patch set in one reproducible step.

WHY THIS EXISTS. The individual patches each work, but applying them by hand
leaves a binary nobody can rebuild: the order matters, two of them interact, and
every module drops its own `.backup` so an install accumulates a dozen files that
say nothing about what state it is actually in. This module fixes the order once
and rebuilds from a single pristine snapshot every time, so the same inputs always
produce the same bytes.

THE ORDER, AND WHY IT IS THIS ORDER:

    1. vram       Startup fix. Independent of everything else.
    2. tables     Doubles the rasteriser's stack frame to 2048 scanlines. Must come
                  BEFORE needle, because needle's bound has to match the tables that
                  actually exist -- and it relocates 21 displacements, so it wants a
                  function nothing else has touched yet.
    3. needle     Two rasteriser bounds, set to whatever step 2 left. Bigger tables
                  with the old bound gains nothing; a bigger bound with the old
                  tables reinstates the stack smash. They move together or not at all.
    4. aspect     Rewrites the viewport builder; may write a float into .rdata slack.
    5. resolution Immediate operands at four sites plus the menu label.
    6. mapfile    LAST, always. It is generated by scanning .text for call targets,
                  so it has to run after every byte of code has settled, and it
                  appends to the file rather than editing it.

Steps 1-5 never change the file's length; step 6 only appends past the last
section, so the image the loader sees is identical either way.

REBUILD, DON'T LAYER. `apply()` always restores the pristine snapshot first and
replays the whole set. That makes it idempotent for free, makes the result depend
only on the arguments rather than on what happened to be applied before, and
means a bad run is undone by the next good one. The alternative -- patching
whatever is currently on disk -- is how the working binary in this project ended
up unreproducible across fifteen backups.

WHAT THAT COSTS, AND THE CARRY-OVER. Restoring the snapshot reverts every patch
in the file, including the four this module does not own: the write-path
redirect, the module assertion, the head-on panic toggle and the horn-ball
tuning. That used to happen in silence, so "apply this resolution" in the
desktop app also moved the player's logs back under C:\\, un-silenced the
assertion, re-enabled the head-on panic and reset the horn -- with nothing said.
This project's own test bed lost all four that way, twice, during unrelated work.

Layering instead would give up the property above, so `apply()` captures those
four BEFORE it restores the snapshot, re-applies them after, and names each one
in the Report. The carry-over is explicit rather than inherited, so the result
is still a function of (arguments + what the Report says was carried); a rebuild
with carry-over is byte-identical to applying the same patches by hand.
`carry_over=False` gives the bare rebuild and reports what it dropped.

THE TABLE, NOT ONE ENTRY. Resolution IS one of this module's own steps, but it
used to write a single menu index and leave the snapshot's stock values in the
other three -- so a player who had repointed a second slot lost it on the next
rebuild, just as silently. `modes={index: (w, h)}` now sets as many entries as
you like in one reproducible call, and any non-stock entry the call does not
mention is carried like the four above. Index 1 is where this matters: its
stock 512x384 is not enumerated by modern drivers, so that menu entry never
appears and the slot is free on every modern machine.

WHICH BINARY. The set follows the engine the install actually RUNS: `race.exe` on
the v1.0 pressing, `race.bin` on v1.1 and the community builds. A v1.0 folder
holds both, and only race.exe is ever loaded, so targeting the name rather than
the live file rewrites a dormant copy and reports success.

THE SNAPSHOT. The first run copies that binary to `<name>.vrmod-original` and
that file is never written again. It is only taken if the binary looks untouched,
so a half-patched file cannot be captured as the baseline; `baseline()` reports
what it found. `revert()` restores it.

Two v1.0 wrinkles follow from the RC shipping with its own linker map appended.
Trailing data past the last section normally means WE put a map there, so
`looks_pristine` would call an untouched race.exe dirty and refuse to snapshot
it; it now asks `mapfile.is_generated` whether the map is ours. And step 6 skips
on such a build -- the shipped map has real symbol names where ours can only
infer `sub_<va>`, so replacing it would be a downgrade even if it were possible.

NOT INCLUDED BY DEFAULT: the DPI-awareness flag. On a high-DPI display the game
is handed a virtualised surface smaller than the mode it asked for and draws
outside it -- see the reference, display-scaling section. That fix is a Windows
per-application setting rather than a change to any game file, so `apply()` only
reports whether it is needed; `set_dpi_aware()` writes it, and the CLI requires
an explicit flag before calling it.
"""
from __future__ import annotations

import hashlib
import shutil
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from . import aspectfix, mapfile, needlefix, resolution, tablefix, vertexbuffer, vrampatch

RACE_BIN = "race.bin"

# The four modes a stock engine ships with, in its own table order.
# Anything else means a resolution patcher has rewritten it.
STOCK_MODES = [(1024, 768), (800, 600), (640, 480), (512, 384)]

# Engine binaries, live one first. The v1.0 pressing runs race.exe and ships a
# race.bin beside it that nothing loads, so the whole set has to follow the live
# binary or it rewrites a dormant file and reports success.
ENGINE_NAMES = ("race.exe", RACE_BIN)

# The snapshot is named after whichever binary it was taken from, so a folder
# holding both cannot end up with one file's baseline restored over the other's.
SNAPSHOT_SUFFIX = ".vrmod-original"
SNAPSHOT = RACE_BIN + SNAPSHOT_SUFFIX          # retained: older installs have this

DEFAULT_MODE = (1920, 1080)
DEFAULT_INDEX = 4               # menu index; 2 is the boot gate and must not be used


class PatchSetError(RuntimeError):
    """The install is not in a state this can safely work from."""


@dataclass
class Report:
    baseline: str = ""
    steps: list[tuple[str, str]] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def add(self, name: str, detail: str) -> None:
        self.steps.append((name, detail))


def _race_bin(data_dir: str | Path) -> Path:
    """The engine binary this install actually runs."""
    d = Path(data_dir)
    for n in ENGINE_NAMES:
        if (d / n).is_file():
            return d / n
    raise PatchSetError(f"no {' or '.join(ENGINE_NAMES)} in {d}")


def _snapshot_path(data_dir: str | Path) -> Path:
    """Where this install's pristine baseline lives, named for its engine."""
    d = Path(data_dir)
    eng = _race_bin(d)
    new = d / (eng.name + SNAPSHOT_SUFFIX)
    if not new.exists() and eng.name == RACE_BIN and (d / SNAPSHOT).exists():
        return d / SNAPSHOT                    # a baseline taken before the rename
    return new


def looks_pristine(data_dir: str | Path) -> tuple[bool, str]:
    """Is this race.bin untouched by us? Returns (verdict, reason).

    The VRAM fix is deliberately not part of the test: the community v1.2.5 build
    ships with it already applied, and that build is a perfectly good baseline.
    """
    d = Path(data_dir)
    if needlefix.status(d) != needlefix.UNPATCHED:
        return False, f"needle fix is {needlefix.status(d)}"
    if aspectfix.status(d) != aspectfix.UNPATCHED:
        return False, f"aspect fix is {aspectfix.status(d)}"
    _, _, trailing = mapfile.status(d)
    if trailing and mapfile.is_generated(_race_bin(d).read_bytes()):
        return False, f"{trailing:,} bytes appended after the last section (our symbol map)"
    if trailing:
        # The v1.0 race.exe is a Release Candidate that SHIPPED with its own
        # linker map appended. That is the untouched file, not a patched one.
        return True, f"no vrmod patches detected ({trailing:,} bytes of the build's own map)"
    return True, "no vrmod patches detected"


def baseline(data_dir: str | Path) -> str:
    """Describe the snapshot this install would rebuild from."""
    d = Path(data_dir)
    snap = _snapshot_path(d)
    if snap.exists():
        return f"{snap.name} ({snap.stat().st_size:,} bytes)"
    eng = _race_bin(d).name
    ok, why = looks_pristine(d)
    return (f"none yet; the current {eng} would be captured ({why})" if ok
            else f"none yet, and the current {eng} is NOT clean: {why}")


# Engine binaries known to be untouched, by sha256. Both race.bin hashes were
# read off the retail discs (1.0 cross-checked against the redump-61183 copy,
# 1.1 off the mounted Rev 1 disc); the race.exe hash comes from that same
# verified 1.0 tree, whose race.bin matches the 1.0 entry below exactly.
#
# doctor derives its edition lookup from this, so there is one table rather than
# two that can drift. (doctor imports patchset, so the dependency runs this way.)
STOCK_ENGINES: dict[str, tuple[str, str]] = {
    "2e3d9dcd7f89af508b1454a46109bbdb2e41ab8b772ab3ae46e294b12a6cdfdf":
        (RACE_BIN, "1.0"),
    "369cb5efd2639d99ad872b9ba5066513ea05cbaf374c526cec0eae3b57205185":
        (RACE_BIN, "1.1"),
    "739619fd213c1e8c234b4712b2bae2a8b362d19f94f6be08c477a42e39d6dd81":
        ("race.exe", "1.0"),
}


def _stock_by_index() -> dict[int, tuple[int, int]]:
    """The stock table keyed by MENU INDEX rather than by slot.

    resolution.read() returns the table in slot order, and the labels run
    descending, so index = MODES - slot. Keying by index is what callers think
    in -- it is what --set and set_mode take.
    """
    return {resolution.MODES - s: wh for s, wh in enumerate(STOCK_MODES)}


def _modes_by_index(d: Path) -> dict[int, tuple[int, int]]:
    return {resolution.MODES - s: wh for s, wh in enumerate(resolution.read(d))}


def _effective_modes(mode: tuple[int, int] | None, index: int,
                     modes: dict[int, tuple[int, int]] | None
                     ) -> dict[int, tuple[int, int]]:
    """What the caller asked the table to look like, keyed by menu index.

    `mode`/`index` name the primary entry and keep their historical meaning;
    `modes` adds to it and wins on a clash, so passing only `modes` still gets
    the default 1920x1080 at index 4. Pass mode=None to set nothing but `modes`.

    Validated here, before apply() restores the snapshot, so a bad request
    cannot leave a half-rebuilt binary behind.
    """
    eff: dict[int, tuple[int, int]] = {}
    if mode is not None:
        eff[index] = mode
    for i, wh in (modes or {}).items():
        eff[int(i)] = (int(wh[0]), int(wh[1]))
    for i, (w, h) in eff.items():
        if not 1 <= i <= resolution.MODES:
            raise PatchSetError(
                f"menu index must be 1-{resolution.MODES}, got {i}")
        if i == resolution.BOOT_GATE_INDEX:
            raise PatchSetError(
                f"menu index {resolution.BOOT_GATE_INDEX} is the startup gate: its "
                f"availability flag is what the game checks before it will start at "
                f"all, so pointing it at a mode the driver does not offer stops the "
                f"game booting. Use another index.")
        if w < 100 or h < 100:
            raise PatchSetError(f"index {i}: {w}x{h} is not a usable mode")
    return eff


@dataclass
class CarryOver:
    """Patches this module does not own, captured before a rebuild.

    apply() restores the pristine snapshot before replaying its own steps --
    that is what makes it idempotent and its output a function of its arguments.
    The cost is that everything ELSE anyone applied to the engine goes with it:
    the write-path redirect, the module assertion, the head-on panic toggle and
    the horn-ball tuning all live in the same binary and are all reverted, in
    silence. Someone who presses "apply this resolution" gets their logs back in
    C:\\ and their mouse panic back, and nothing says so.

    So they are captured first and re-applied after, and every one is reported.
    Determinism is kept because the carry-over is explicit and visible in the
    Report rather than inherited by accident -- and `carry_over=False` gives the
    genuinely bare rebuild, which then says what it dropped.
    """
    writepath_kinds: list[str] = field(default_factory=list)
    modassert: bool = False
    headon_disabled: bool = False
    hornball: tuple[float, float] | None = None
    # Menu index -> mode, for entries that are not stock. Resolution IS one of
    # this module's own steps, but it only ever set ONE index, so any other slot
    # the player had repointed went back to stock on the next rebuild -- and
    # index 1 is dead on modern hardware (512x384 is not enumerated), so that
    # spare slot is exactly where a second mode tends to live.
    resolution: dict[int, tuple[int, int]] = field(default_factory=dict)

    def __bool__(self) -> bool:
        return bool(self.writepath_kinds or self.modassert
                    or self.headon_disabled or self.hornball or self.resolution)

    def describe(self) -> list[str]:
        out = [f"write paths ({k})" for k in self.writepath_kinds]
        out += [f"menu index {i} at {w}x{h}"
                for i, (w, h) in sorted(self.resolution.items())]
        if self.modassert:
            out.append("module assertion silenced")
        if self.headon_disabled:
            out.append("head-on panic disabled")
        if self.hornball:
            out.append(f"horn ball {self.hornball[0]:.2f}x / {self.hornball[1]:.2f}s")
        return out


def _capture(d: Path) -> CarryOver:
    """What is applied to this engine that the patch set does not own."""
    from . import headon, hornball, modassert, writepaths
    c = CarryOver()
    try:
        live = _race_bin(d).name
        for kind, state in writepaths.status(d).get(live, {}).items():
            if state == "patched":
                c.writepath_kinds.append(kind)
    except Exception:
        pass
    try:
        c.modassert = modassert.status(d) == modassert.PATCHED
    except Exception:
        pass
    try:
        c.headon_disabled = headon.status(d) == headon.DISABLED_STATE
    except Exception:
        pass
    try:
        if hornball.available(d):
            t = hornball.read(d)
            if not t.is_stock:
                c.hornball = (t.speed_mult, t.cooldown)
    except Exception:
        pass
    try:
        stock = _stock_by_index()
        c.resolution = {i: wh for i, wh in _modes_by_index(d).items()
                        if wh != stock[i]}
    except Exception:
        pass
    return c


def _reapply(d: Path, c: CarryOver, rep: "Report") -> None:
    """Put the captured patches back, reporting each one."""
    from . import headon, hornball, modassert, writepaths
    for kind in c.writepath_kinds:
        try:
            writepaths.apply(d, kind, migrate=False)
            rep.add("carried", f"write paths ({kind}) re-applied")
        except Exception as e:
            rep.notes.append(f"could not re-apply the {kind} write paths: {e}")
    if c.modassert:
        try:
            modassert.apply(d)
            rep.add("carried", "module assertion silenced again")
        except Exception as e:
            rep.notes.append(f"could not re-silence the module assertion: {e}")
    if c.headon_disabled:
        try:
            headon.apply(d)
            rep.add("carried", "head-on panic disabled again")
        except Exception as e:
            rep.notes.append(f"could not re-disable the head-on panic: {e}")
    if c.hornball:
        speed, cool = c.hornball
        try:
            hornball.apply(d, speed_mult=speed, cooldown=cool)
            rep.add("carried", f"horn ball re-tuned to {speed:.2f}x / {cool:.2f}s")
        except Exception as e:
            rep.notes.append(f"could not re-tune the horn ball: {e}")


def _patch_score(d: Path) -> int:
    """How many of this toolkit's patches a folder's engine carries.

    Only used to rank candidates when no hash matches. looks_pristine() is
    deliberately lenient -- it ignores the VRAM fix, because the community
    v1.2.5 build ships with it and is a perfectly good baseline -- so it cannot
    tell an untouched file from one that is merely missing the needle and aspect
    fixes. Without this, a `.needle-backup` taken after four other patches
    scores the same as the original.
    """
    from . import headon, modassert, writepaths        # local: avoid import cycles
    score = 0
    try:
        if vrampatch.status(d) == vrampatch.PATCHED:
            score += 1
        if tablefix.status(d) != tablefix.UNPATCHED:
            score += 1
        if modassert.status(d) == modassert.PATCHED:
            score += 1
        if headon.status(d) == headon.DISABLED_STATE:
            score += 1
        for st in writepaths.status(d).values():
            score += sum(1 for v in st.values() if v == "patched")
        if resolution.read(d) != STOCK_MODES:
            score += 1
    except Exception:
        pass
    return score


def find_pristine_backup(data_dir: str | Path) -> tuple[Path, str] | None:
    """An untouched copy of the engine among the backups we already made.

    Returns (path, why) or None. Every patch in this toolkit drops a
    `<engine>.<name>-backup` beside the file it edits, so on an install that was
    patched a tool at a time -- which has no `.vrmod-original` -- the copy taken
    before the FIRST patch is the original, sitting right there. Telling someone
    to go find their disc while holding one of their own copies is a poor trade.

    Ranked, best first:

      1. an exact sha256 match against STOCK_ENGINES -- definitive;
      2. otherwise the candidate carrying the FEWEST of our patches, which is
         the best that can be said without a known hash. looks_pristine() alone
         is not enough here: it ignores the VRAM fix by design, so a backup
         taken after four other patches passes it just as the original does.

    Each candidate is tested by copying it into a temp directory under the
    engine's own name -- the real install is never touched.
    """
    d = Path(data_dir)
    eng = _race_bin(d)
    size = eng.stat().st_size
    cands = [p for p in d.glob(eng.name + ".*")
             if p.is_file() and p != eng
             and (p.name.endswith("-backup") or p.name.endswith(SNAPSHOT_SUFFIX))
             and p.stat().st_size == size]

    best: tuple[int, float, Path, str] | None = None
    for c in sorted(cands, key=lambda p: p.stat().st_mtime):
        try:
            blob = c.read_bytes()
        except OSError:
            continue                              # unreadable candidate: skip it
        known = STOCK_ENGINES.get(hashlib.sha256(blob).hexdigest())
        if known is not None and known[0] == eng.name:
            return c, f"byte-identical to the retail {known[1]} {eng.name}"
        tmp = Path(tempfile.mkdtemp(prefix="vrmod_pristine_"))
        try:
            shutil.copy2(c, tmp / eng.name)
            ok, _ = looks_pristine(tmp)
            if ok:
                score = _patch_score(tmp)
                if best is None or score < best[0]:
                    best = (score, c.stat().st_mtime, c,
                            "carries none of the fixes this tool re-applies"
                            if score == 0 else
                            f"the least-patched copy here, though it already "
                            f"carries {score} of this tool's changes")
        except Exception:
            continue
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
    return (best[2], best[3]) if best else None


def _snapshot(data_dir: Path, force: bool) -> Path:
    snap = _snapshot_path(data_dir)
    if snap.exists():
        return snap
    eng = _race_bin(data_dir)
    ok, why = looks_pristine(data_dir)
    if not ok and not force:
        found = find_pristine_backup(data_dir)
        if found is not None:
            src, reason = found
            raise PatchSetError(
                f"refusing to snapshot a patched {eng.name} as the baseline: {why}.\n"
                f"{src.name} is a better baseline -- {reason}. Restore it and run "
                f"this again:\n"
                f'    copy "{src.name}" "{eng.name}"\n'
                f"(Or pass force=True to freeze the current, patched file as the "
                f"baseline forever, which is almost never what you want: every later "
                f"rebuild and every revert would keep those patches.)")
        raise PatchSetError(
            f"refusing to snapshot a patched {eng.name} as the baseline: {why}.\n"
            f"No untouched copy was found among this folder's backups either, so "
            f"restore an original {eng.name} from your disc first -- or pass "
            f"force=True if you are certain this file is the one you want to "
            f"rebuild from every time.")
    shutil.copy2(eng, snap)
    return snap


def status(data_dir: str | Path) -> dict[str, str]:
    """Current state of every component."""
    d = Path(data_dir)
    size, image_end, trailing = mapfile.status(d)
    try:
        modes = ", ".join(f"{m.index}:{m.width}x{m.height}" for m in resolution.modes(d))
    except Exception as exc:                       # a mode table we don't recognise
        modes = f"<{type(exc).__name__}>"
    return {
        "baseline": baseline(d),
        "vram": vrampatch.status(d),
        "tables": f"{tablefix.status(d)} ({tablefix.entries(d)} entries per table)",
        "needle": needlefix.status(d),
        "aspect": aspectfix.status(d),
        "vertices": vertexbuffer.status(d),
        "resolution": modes,
        "mapfile": f"{trailing:,} bytes appended" if trailing else "not installed",
        "size": f"{size:,} bytes",
    }


def apply(data_dir: str | Path,
          *,
          mode: tuple[int, int] | None = DEFAULT_MODE,
          index: int = DEFAULT_INDEX,
          modes: dict[int, tuple[int, int]] | None = None,
          with_map: bool = True,
          big_tables: bool = True,
          ratio: float = aspectfix.RATIO_ORIGINAL,
          max_verts: int | None = None,
          force_baseline: bool = False,
          carry_over: bool = True) -> Report:
    """Rebuild race.bin from the pristine snapshot with the full patch set.

    mode/index name the primary entry; `modes` is a {menu index: (w, h)} map
    that adds further entries and wins on a clash, so the whole four-slot table
    can be set in one reproducible call. mode=None sets nothing but `modes`.
    Index 2 is refused either way -- its availability flag gates startup.

    carry_over: re-apply what the rebuild would otherwise silently revert --
    the write paths, module assertion, head-on toggle and horn-ball tuning,
    plus any table entry the player had repointed and did not name in this
    call. On by default, because losing them silently is the worse surprise;
    every one is listed in the Report. Pass False for a genuinely bare rebuild
    -- it then reports what it dropped.
    """
    d = Path(data_dir)
    f = _race_bin(d)
    rep = Report()
    # Validate the whole request before anything is written, so a bad index
    # cannot leave a half-rebuilt binary on disk.
    requested = _effective_modes(mode, index, modes)

    snap = _snapshot(d, force_baseline)
    rep.baseline = f"{snap.name} ({snap.stat().st_size:,} bytes)"
    # Capture BEFORE the snapshot goes back: restoring it reverts every patch in
    # the file, including the ones that are none of this module's business.
    carried = _capture(d)
    shutil.copy2(snap, f)                          # start clean, every time

    # 1 -- startup
    if vrampatch.status(d) == vrampatch.PATCHED:
        rep.add("vram", "already correct in this build (v1.2.5 ships it)")
    else:
        rep.add("vram", f"patched at {hex(vrampatch.apply(d))}")

    # 2 -- rasteriser: grow the tables first, then bound to whatever they now hold.
    #      These two MUST agree. Bigger tables with the old bound gains nothing;
    #      a bigger bound with the old tables reinstates the stack smash.
    if big_tables:
        info = tablefix.apply(d)
        if info["result"] == "patched":
            rep.add("tables", f"frame 0x2000 -> 0x4000 at {info['at']:#x}: "
                              f"{info['table_b_refs']} table-B and {info['arg_refs']} "
                              f"argument references relocated, 2048 entries each")
        else:
            rep.add("tables", str(info["result"]))
    else:
        rep.add("tables", "left at 1024 entries (--small-tables)")

    bound = tablefix.entries(d)
    for site, detail in needlefix.apply(d, entries=bound).items():
        rep.add(f"needle/{site}", detail)

    # 3 -- viewport / field of view
    at, r0, half = aspectfix.apply(d, ratio)
    rep.add("aspect", f"Hor+ at R0={ratio:.4f}, patched at {hex(at)} "
                      f"(constants {hex(r0)}, {hex(half)})")

    # 4 -- resolution. The whole TABLE, not one entry: anything the player had
    #      repointed and did not name in this call is carried, because the
    #      snapshot restore above put every slot back to stock.
    table = dict(requested)
    if carry_over:
        for i, wh in carried.resolution.items():
            table.setdefault(i, wh)
    for i in sorted(table):
        w, h = table[i]
        was = resolution.set_mode(d, i, w, h)
        how = "" if i in requested else "  (carried)"
        rep.add("resolution", f"menu index {i}: {was[0]}x{was[1]} -> {w}x{h}{how}")

    rows = tablefix.entries(d)
    for i, (w, h) in sorted(table.items()):
        if h - 0x50 >= rows:
            rep.notes.append(
                f"{w}x{h} (index {i}) pivots the tachometer needle at row "
                f"{h - 0x50}, past the {rows}-scanline edge tables, so the NEEDLE "
                f"will not be drawn. The dial itself is unaffected."
                + ("" if big_tables else
                   " Dropping --small-tables would raise the tables to 2048 and "
                   "fix it."))
        if w > 2048:
            rep.notes.append(
                f"{w} (index {i}) is wider than 2048, which legacy Direct3D "
                f"surfaces cap at. Expect 'create device' / DDERR_INVALIDOBJECT "
                f"and a misleading 'requires DirectX 5 or 6' dialog from the "
                f"launcher.")

    # 5b -- per-object vertex buffer (OPT-IN). Off unless a size is asked for,
    #       because the stock cap suits every stock car and raising it only helps
    #       high-poly mods (and, at worst, trades frames for detail with many such
    #       cars -- it cannot crash, rendering being per-object; see vertexbuffer).
    if max_verts is None:
        rep.add("vertices", f"left at stock ({vertexbuffer.status(d)}); "
                            f"raise with --max-verts")
    else:
        info = vertexbuffer.apply(d, max_verts)
        rep.add("vertices", f"buffer {info['old_verts']:,} -> {info['new_verts']:,} "
                            f"verts/object at {info['at']:#x}")

    # 6 -- symbols, last
    if not with_map:
        rep.add("mapfile", "skipped")
    else:
        _, _, trailing = mapfile.status(d)
        if trailing and not mapfile.is_generated(f.read_bytes()):
            # The v1.0 race.exe already carries its OWN linker map -- 10,000-odd
            # real names against the sub_<va> placeholders we can infer. Appending
            # ours would sit after it and be parsed as a continuation, and would
            # be the worse map anyway.
            have, _src = mapfile.symbols(d)
            rep.add("mapfile", f"left alone: this build ships its own map "
                               f"({len(have):,} symbols, {trailing:,} bytes)")
        else:
            syms, added = mapfile.install(d)
            rep.add("mapfile", f"{syms:,} symbols, {added:,} bytes appended")

    # 7 -- everything this module does not own, put back after the rebuild.
    #      Last, so it lands on a finished binary; all four are in-place edits
    #      that move nothing, so the symbol map written in step 6 stays valid.
    if carried and carry_over:
        _reapply(d, carried, rep)
    elif carried:
        rep.notes.append(
            "Rebuilt without carry-over, so these were reverted along with the "
            "snapshot and are NOT back: " + "; ".join(carried.describe()) + ".")

    if not dpi_aware(d):
        rep.notes.append(
            "This machine scales the desktop, so the game will be handed a surface "
            "smaller than the mode it asks for and will draw outside it. Set the "
            "launcher to be DPI-aware (see set_dpi_aware) before judging any "
            "high-resolution rendering.")
    return rep


def revert(data_dir: str | Path) -> str:
    """Put the pristine snapshot back."""
    d = Path(data_dir)
    snap = _snapshot_path(d)
    if not snap.exists():
        raise PatchSetError(f"no {snap.name} to restore from")
    eng = _race_bin(d)
    shutil.copy2(snap, eng)
    return f"restored {eng.name} from {snap.name} ({snap.stat().st_size:,} bytes)"


# --------------------------------------------------------------------------
# the Windows side
# --------------------------------------------------------------------------

LAYERS_KEY = r"Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"
LAUNCHER = "Viper Racing.exe"
RACE_EXE = "race.exe"   # v1.0's engine -- see _dpi_targets()


def _dpi_targets(data_dir: str | Path) -> list[Path]:
    """The executables a DPI compatibility layer may need to sit on.

    Two candidates, because which one Windows honours is genuinely ambiguous:

      * `race.bin` -- the REAL game process. `Viper Racing.exe` only
        `CreateProcess`-es it and imports no graphics DLLs, so race.bin is what
        owns the window and renders (it imports DDRAW/DSOUND). Windows tracks it
        as a program in its own right -- the Program Compatibility Assistant
        auto-adds a `DWM8And16BitMitigation` layer to the race.bin path -- so a
        layer keyed to race.bin is honoured despite the `.bin` extension.
      * `Viper Racing.exe` -- the launcher. Empirically, setting HIGHDPIAWARE
        here ALSO fixes rendering, most likely because a compatibility shim set
        on a parent propagates to the child it spawns.

    So the flag is set on both, and considered present if either has it. An
    earlier version targeted only the launcher, and named it "the process that
    owns the window", which is wrong -- race.bin is.

    On a v1.0 install neither of those is the game: `race.exe` is the engine, and
    Data's contents ARE the install directory, so there is no launcher in the
    parent. Flagging only race.bin there sets the layer on a file the build never
    loads and the scaling is not fixed, with nothing to say the flag went
    nowhere. race.exe is therefore included, and listed first.

    The launcher is looked for in BOTH places: an installed 1.1 tree keeps it in
    the parent beside Data\\, but on the retail disc it ships INSIDE Data\\ and
    only moves up when SETUP runs. Checking one location means missing it
    whenever the folder being examined is the disc itself.
    """
    d = Path(data_dir)
    return [d / RACE_EXE, d / RACE_BIN, d.parent / LAUNCHER, d / LAUNCHER]


def scaling_active() -> bool | None:
    """Is the desktop being scaled for DPI-unaware processes? None if unknowable."""
    try:
        import ctypes
        user32 = ctypes.windll.user32
        virt_w = user32.GetSystemMetrics(0)                 # what an unaware app sees
        real_w = ctypes.windll.gdi32.GetDeviceCaps(
            user32.GetDC(0), 118)                           # DESKTOPHORZRES: physical
        return bool(real_w and virt_w and real_w != virt_w)
    except Exception:
        return None


def dpi_aware(data_dir: str | Path) -> bool:
    """Is the HIGHDPIAWARE layer WRITTEN for any of this install's executables?

    ⚠️ This reports what is in the registry, NOT that the layer is in effect.
    They are not the same thing, and the gap is reproducible: writing
    `~ HIGHDPIAWARE` here can leave the game still rendering DPI-unaware, while
    setting the identical value through Properties -> Compatibility -> Change
    high DPI settings fixes it immediately. Confirmed by comparing the two --
    the stored value was byte-for-byte the same either way, so the difference is
    not what is written but that the dialog also refreshes the AppCompat shim
    cache, which a bare registry write does not.

    So treat a True here as "the setting is recorded", and the Compatibility
    dialog as the authority on whether it applies.
    """
    try:
        import winreg
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, LAYERS_KEY) as k:
            for exe in _dpi_targets(data_dir):
                try:
                    if "HIGHDPIAWARE" in winreg.QueryValueEx(k, str(exe))[0]:
                        return True
                except FileNotFoundError:
                    continue
    except Exception:
        pass
    return False


def set_dpi_aware(data_dir: str | Path, enable: bool = True) -> str:
    """Add or remove the launcher's HIGHDPIAWARE layer for the current user.

    This writes to HKEY_CURRENT_USER only and is exactly what the Compatibility
    tab writes when you tick "Override high DPI scaling behavior -- Scaling
    performed by: Application". Callers should make this an explicit choice
    rather than part of a default install.

    ⚠️ WRITING IT IS NOT THE SAME AS IT TAKING EFFECT. Observed repeatedly: the
    value lands correctly and the game still renders DPI-unaware, then setting
    the SAME value through the dialog fixes it at once. The stored strings were
    compared and are identical, so the dialog is doing something besides writing
    -- refreshing the shim cache -- that this cannot reproduce. Always tell the
    user the dialog is the fallback; never report this as a completed fix.
    """
    import winreg
    targets = [e for e in _dpi_targets(data_dir) if e.is_file()]
    if not targets:
        raise PatchSetError(
            f"no {RACE_EXE}, {RACE_BIN} or {LAUNCHER} to flag in {data_dir}")
    key = winreg.CreateKey(winreg.HKEY_CURRENT_USER, LAYERS_KEY)
    results = []
    try:
        for exe in targets:
            try:
                current = winreg.QueryValueEx(key, str(exe))[0]
            except FileNotFoundError:
                current = ""
            # keep any existing layers (e.g. the PCA's DWM8And16BitMitigation);
            # only add or remove HIGHDPIAWARE.
            layers = [t for t in current.split() if t not in ("HIGHDPIAWARE", "~")]
            if enable:
                layers.insert(0, "HIGHDPIAWARE")
            if layers:
                winreg.SetValueEx(key, str(exe), 0, winreg.REG_SZ, " ".join(["~"] + layers))
                results.append(f"{exe.name}: {' '.join(['~'] + layers)}")
            else:
                try:
                    winreg.DeleteValue(key, str(exe))
                    results.append(f"{exe.name}: compatibility layers cleared")
                except FileNotFoundError:
                    results.append(f"{exe.name}: nothing to clear")
    finally:
        winreg.CloseKey(key)
    return "; ".join(results)
